version: '3'
services:
    app:
        # 要変更: my_app → コンテナ名
        container_name: "my_app"
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        # 要変更: myapp →プロジェクト名
        volumes: 
            - .:/my_app
        ports:
            - "3000:3000"
        depends_on: 
            - db
    db:
        # 要変更: my_app_db → DB名
        container_name: "my_app_db"
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: my_app_db
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
        command: mysqld --character-set-server=utf8